#!/usr/bin/env sh

echo "Running Spotless check..."

./gradlew spotlessCheck
RESULT=$?

if [ "$RESULT" -ne 0 ]; then
    echo ""
    echo "Spotless found formatting violations."
    echo "Commit has been cancelled."
    echo ""
    echo "Fix formatting with:"
    echo "  ./gradlew spotlessApply"
    echo ""
    exit "$RESULT"
fi

echo "Spotless check passed."

echo "Running Detekt check..."
./gradlew detektAll
RESULT=$?

if [ "$RESULT" -ne 0 ]; then
  echo ""
  echo "Detekt found problems with code."
  echo "Commit has been cancelled."
  echo ""
  exit "$RESULT"
fi

echo "Detekt check passed."

exit 0