name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:

    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Run lint
          uses: ./gradlew lintDebug

        - name: Upload lint test report
          uses: actions/upload-artifact@v2
          with:
            name: lint.html
            path: app/build/reports/lint-results-debug.html

    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Run unit tests
          uses: ./gradlew test

        - name: Upload unit test report
          uses: actions/upload-artifact@v2
          with:
            name: unit_test_report
            path: app/build/reports/test/testDebugUnitTest/

    build-debug-apk:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Set up Java
          uses: actions/setup-java@v1
          with:
            java-version: '17'

        - name: Assemble apk
          uses: ./gradlew assembleDebug --stacktrace

        - name: Upload apk
          uses: actions/upload-artifact@v2
          with:
            name: debug.apk
            path: app/build/outputs/apk/debug/app-debug.apk
