name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:

    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Grant execute permission for Gradle
          run: chmod +x ./gradlew

        - name: Run lint
          run: ./gradlew lintDebug

        - name: Upload lint test report
          uses: actions/upload-artifact@v4
          with:
            name: lint.html
            path: app/build/reports/lint-results-debug.html

    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Grant execute permission for Gradle
          run: chmod +x ./gradlew

        - name: Run unit tests
          run: ./gradlew test

        - name: Upload unit test report
          uses: actions/upload-artifact@v4
          with:
            name: unit_test_report
            path: app/build/reports/test/testDebugUnitTest/

    build-debug-apk:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: '17'
            cache: gradle

        - name: Grant execute permission for Gradle
          run: chmod +x ./gradlew

        - name: Assemble apk
          run: ./gradlew assembleDebug --stacktrace

        - name: Upload apk
          uses: actions/upload-artifact@v4
          with:
            name: debug.apk
            path: app/build/outputs/apk/debug/app-debug.apk
            if-no-files-found: error

    build-signed-apk:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: '17'
            cache: gradle

        - name: Grant execute permission for Gradle
          run: chmod +x ./gradlew

        - name: Build Release APK
          run: ./gradlew assembleRelease

        - name: Sign APK
          uses: r0adkll/sign-android-release@v1
          id: sign_app
          with:
            releaseDirectory: app/build/outputs/apk/release
            signingKeyBase64: ${{ secrets.SIGNING_KEY }}
            alias: ${{ secrets.KEY_ALIAS }}
            keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
            keyPassword: ${{ secrets.KEY_PASSWORD }}

        - name: Upload Signed APK
          uses: actions/upload-artifact@v4
          with:
            name: app-signed
            path: app/build/outputs/apk/release/*.apk
